### ISSUE TITLE
missing rtf modulo

### ISSUE THREAD

**Issue by pachadotdev** [jnavila/graffle2svg#16]
when trying to use it, the console returns

```
graffle2svg ../diagrams/en/action-layout.graffle ../diagrams_svg/en/action-layout.graffle
Traceback (most recent call last):
  File "/usr/local/bin/graffle2svg", line 4, in <module>
    __import__('pkg_resources').run_script('graffle2svg==0.4.dev0', 'graffle2svg')
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 667, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1470, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python3.8/dist-packages/graffle2svg-0.4.dev0-py3.8.egg/EGG-INFO/scripts/graffle2svg", line 19, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "/usr/local/lib/python3.8/dist-packages/graffle2svg-0.4.dev0-py3.8.egg/graffle2svg/main.py", line 16, in <module>
ModuleNotFoundError: No module named 'rtf'
```

**Comment by jnavila** [comment]
This project has been working with very early version of python 3, but it is no longer up to date with the latest versions.


It definitely needs to be archived. I don't intend to work on it... Please fork it if you intend to fix it.
